. /etc/bash.bashrc
. $HOME/.color.bashrc

PS1="\[\033[1;31m\]\h \[\033[1;33m\]\w \[\033[1;34m\]\$ \[\033[0;32m\]"

setupbash() { wget -O color.bashrc https://gist.githubusercontent.com/mvidaldp/8051523f75669a627553f1a3c943d655/raw/842659a50bcca90efb2bebfbe6e5b9b24c62e9fb/.bashrc }
